![](https://koyomi.oss-cn-hangzhou.aliyuncs.com/20200209134347.png)

# 数据预处理

In [31]:
import pandas as pd
import numpy as np

In [32]:
train_file = "./5-1.csv"
train_data = pd.read_csv(train_file)

In [33]:
print(train_data)

    ID  年龄 有工作 有自己的房子 信贷情况 类别
0    1  青年   否      否   一般  否
1    2  青年   否      否    好  否
2    3  青年   是      否    好  是
3    4  青年   是      是   一般  是
4    5  青年   否      否   一般  否
5    6  中年   否      否   一般  否
6    7  中年   否      否    好  否
7    8  中年   是      是    好  是
8    9  中年   否      是  非常好  是
9   10  中年   否      是  非常好  是
10  11  老年   否      是  非常好  是
11  12  老年   否      是    好  是
12  13  老年   是      否    好  是
13  14  老年   是      否  非常好  是
14  15  老年   否      否   一般  否

In [34]:
type(train_data)

pandas.core.frame.DataFrame

In [35]:
train_data.head()

   ID  年龄 有工作 有自己的房子 信贷情况 类别
0   1  青年   否      否   一般  否
1   2  青年   否      否    好  否
2   3  青年   是      否    好  是
3   4  青年   是      是   一般  是
4   5  青年   否      否   一般  否

In [36]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
ID        15 non-null int64
年龄        15 non-null object
有工作       15 non-null object
有自己的房子    15 non-null object
信贷情况      15 non-null object
类别        15 non-null object
dtypes: int64(1), object(5)
memory usage: 800.0+ bytes

In [47]:
age_data = train_data['年龄'].copy()
age_data

0     青年
1     青年
2     青年
3     青年
4     青年
5     中年
6     中年
7     中年
8     中年
9     中年
10    老年
11    老年
12    老年
13    老年
14    老年
Name: 年龄, dtype: object

In [48]:
for i,x in enumerate(age_data):
    if x == '青年':
        age_data[i] = 1
    elif x == '中年':
        age_data[i] = 2
    elif x == '老年':
        age_data[i] = 3

train_data['年龄'] = age_data

In [49]:
train_data

    ID 年龄 有工作 有自己的房子 信贷情况 类别
0    1  1   否      否   一般  否
1    2  1   否      否    好  否
2    3  1   是      否    好  是
3    4  1   是      是   一般  是
4    5  1   否      否   一般  否
5    6  2   否      否   一般  否
6    7  2   否      否    好  否
7    8  2   是      是    好  是
8    9  2   否      是  非常好  是
9   10  2   否      是  非常好  是
10  11  3   否      是  非常好  是
11  12  3   否      是    好  是
12  13  3   是      否    好  是
13  14  3   是      否  非常好  是
14  15  3   否      否   一般  否

In [55]:
work_data = train_data['有工作'].copy()
for i,x in enumerate(work_data):
    if x == '是':
        work_data[i] = 1
    if x == '否':
        work_data[i] = 2
train_data['有工作'] = work_data

In [56]:
train_data

    ID 年龄 有工作 有自己的房子 信贷情况 类别
0    1  1   2      否   一般  否
1    2  1   2      否    好  否
2    3  1   1      否    好  是
3    4  1   1      是   一般  是
4    5  1   2      否   一般  否
5    6  2   2      否   一般  否
6    7  2   2      否    好  否
7    8  2   1      是    好  是
8    9  2   2      是  非常好  是
9   10  2   2      是  非常好  是
10  11  3   2      是  非常好  是
11  12  3   2      是    好  是
12  13  3   1      否    好  是
13  14  3   1      否  非常好  是
14  15  3   2      否   一般  否

In [61]:
house_data = train_data['有自己的房子'].copy()
for i,x in enumerate(house_data):
    if x == '是':
        house_data[i] = 1
    if x == '否':
        house_data[i] = 2
train_data['有自己的房子'] = house_data

In [62]:
loan_data = train_data['信贷情况'].copy()
for i,x in enumerate(loan_data):
    if x == '非常好':
        loan_data[i] = 1
    if x == '好':
        loan_data[i] = 2
    if x == '一般':
        loan_data[i] = 3
train_data['信贷情况'] = loan_data

In [63]:
train_data

    ID 年龄 有工作 有自己的房子 信贷情况 类别
0    1  1   2      2    3  否
1    2  1   2      2    2  否
2    3  1   1      2    2  是
3    4  1   1      1    3  是
4    5  1   2      2    3  否
5    6  2   2      2    3  否
6    7  2   2      2    2  否
7    8  2   1      1    2  是
8    9  2   2      1    1  是
9   10  2   2      1    1  是
10  11  3   2      1    1  是
11  12  3   2      1    2  是
12  13  3   1      2    2  是
13  14  3   1      2    1  是
14  15  3   2      2    3  否

# 用C4.5建树

In [66]:
from treelib import Node,Tree

ModuleNotFoundError: No module named 'treelib'